version: '3.5'
services:
#  swift:
#    build: ios/.
#    restart: always
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./ios:/app/src/ios
#    links:
#      - api
  react:
    build: react-front/.
    env_file:
      - .env
    command: bash -c "expo login --username ${USERNAME} --password ${PASSWORD} && yarn start --tunnel"
    restart: always
    volumes:
      - ./react-front:/app
      - /app/node_modules/
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    links:
      - api
  api:
      build: api/.
      command: yarn start
      restart: always
      volumes:
        - ./api:/api
        - /api/node_modules/
      ports:
        - "4242:4242"
#  db:
#    build: db/.
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./db/data:/db/data